import { Link } from 'react-router-dom'
import ResearchExperience from '../components/experience/ResearchExperience'
import MotionReveal from '../components/motion/MotionReveal'
import SignalVisual from '../components/visualizations/SignalVisual'
import { components, evidence, project, safetyPrinciples } from '../data/research'

export default function Home(){return <main className="home-page">
  <ResearchExperience/>
  <section id="research-thesis" className="thesis-section paper-section"><div className="shell-wide thesis-grid"><MotionReveal><p className="eyebrow">RESEARCH THESIS / 2026</p></MotionReveal><MotionReveal delay={.08}><h2>{project.thesis}</h2></MotionReveal><MotionReveal delay={.14}><p>Each modality is evaluated under its own validation contract before it is allowed to influence the integrated evidence state.</p></MotionReveal></div></section>

  <section className="atlas-section dark-section" aria-labelledby="atlas-title"><div className="shell-wide"><div className="section-kicker"><p className="eyebrow light">04 RESEARCH STREAMS</p><h2 id="atlas-title">A vertical atlas of the signals.</h2></div>{components.map((component,i)=><article className={`atlas-stream stream-${component.key}`} key={component.id}><div className="atlas-sticky-id"><span>{component.stateId}</span><strong>{component.id}</strong></div><MotionReveal className="atlas-copy"><p className="eyebrow light">{component.owner}</p><h3>{component.title}</h3><p className="atlas-question">{component.question}</p></MotionReveal><MotionReveal className="atlas-visual" delay={.06}><SignalVisual type={component.key}/></MotionReveal><MotionReveal className="atlas-evidence" delay={.1}><dl><div><dt>METHOD</dt><dd>{component.method}</dd></div><div><dt>DATA</dt><dd>{component.data}</dd></div><div><dt>EVIDENCE STATUS</dt><dd>{component.status}</dd></div>{component.limitation&&<div className="limitation"><dt>LIMITATION</dt><dd>{component.limitation}</dd></div>}</dl>{component.key==='c2'&&<p className="gate-note">Current fusion contribution: <strong>0.0</strong></p>}{component.key==='c3'&&<p className="gate-note">Deployment-relevant held-out AUROC: <strong>≈0.738</strong> · patient-disjoint setting</p>}</MotionReveal></article>)}</div></section>

  <section className="architecture-section paper-section"><div className="shell-wide architecture-grid"><MotionReveal className="architecture-copy"><p className="eyebrow">SYSTEM ARCHITECTURE</p><h2>Integration follows evidence eligibility—not visual symmetry.</h2><p>C1, C2 and C3 are observed as separate research streams. The reliability gate decides whether an available modality is eligible to influence fusion. Under the current evidence gate, C2 is visibly withheld.</p><Link to="/methodology" className="editorial-link" data-cursor="EXPLORE">Explore methodology ↗</Link></MotionReveal><MotionReveal className="architecture-visual" delay={.08}><SignalVisual type="architecture"/></MotionReveal></div></section>

  <section className="evidence-section paper-section"><div className="shell-wide"><div className="section-kicker"><p className="eyebrow">EVIDENCE RECORD</p><h2>Metrics are evidence, not advertisements.</h2><p>Each result remains attached to the setting and interpretation that makes it meaningful.</p></div><div className="evidence-table" role="table" aria-label="Selected research evidence"><div className="evidence-table-head" role="row"><span role="columnheader">Component</span><span role="columnheader">Measure</span><span role="columnheader">Value</span><span role="columnheader">Context / interpretation</span></div>{evidence.map((item,i)=><MotionReveal key={`${item.component}-${item.metric}`} className="evidence-table-row" delay={i*.035}><span>{item.component}</span><div><strong>{item.metric}</strong><small>{item.context}</small></div><b>{item.value}</b><p>{item.note}</p></MotionReveal>)}</div><Link to="/results" className="editorial-link" data-cursor="VIEW">View full evidence record →</Link></div></section>

  <section className="abstention-section"><div className="shell-wide abstention-grid"><p className="eyebrow light">RELIABILITY / ABSTENTION</p><MotionReveal><h2>The system can withhold weak modalities and return insufficient evidence rather than manufacture certainty.</h2></MotionReveal><MotionReveal delay={.08}><p>{safetyPrinciples[0]} {safetyPrinciples[1]}</p><p className="abstain-line">{safetyPrinciples[2]}</p></MotionReveal></div></section>
</main>}
