import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(p)=>fs.readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const home=read('src/pages/Home.jsx');
const nav=read('src/components/Navbar.jsx');
const mobileNav=read('src/components/hero/MobileResearchMenu.jsx');
const navigationText=`${nav}\n${mobileNav}`;
const css=read('src/index.css');
const html=read('index.html');
assert.match(home,/ResearchHero/,'Home must render the modular ResearchHero');
assert.doesNotMatch(home,/ResearchPlate/,'Legacy ResearchPlate must be removed from Home');
assert.match(navigationText,/\/components/,'Desktop/mobile navigation must retain the Research route');
assert.match(navigationText,/\/methodology/,'Navigation must retain Methodology');
assert.match(navigationText,/\/results/,'Navigation must retain Evidence');
assert.match(navigationText,/\/team/,'Navigation must retain Team');
assert.match(navigationText,/\/publications/,'Complete navigation must retain Publications');
assert.match(navigationText,/\/documents/,'Complete navigation must retain Documents');
assert.match(navigationText,/\/contact/,'Complete navigation must retain Contact');
assert.match(css,/\.liquid-glass-light/,'Light liquid-glass material must exist');
assert.match(css,/100svh/,'Hero must use small viewport units');
assert.match(css,/prefers-reduced-motion/,'Reduced-motion support must exist');
assert.match(html,/family=Inter:wght@300;400;500;600;700/,'Inter 300–700 must be loaded from the document head');
console.log('Hero architecture validation passed.');
